service: nodejs-aws-first-app

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-finch

custom:
  client:
    bucketName: nodejs-aws-first-app
    distributionFolder: build
